from sentence_transformers import SentenceTransformer
import faiss, pickle, numpy as np

print("Đang khởi tạo model, vui lòng đợi...")
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# ─────────────────────────────────────────────────────────
# KNOWLEDGE BASE MỞ RỘNG (Bao phủ từ lóng, nói tắt, đa dạng ngữ pháp)
# ─────────────────────────────────────────────────────────
KNOWLEDGE_BASE = [

    # 1. INVENTORY_CHECK (Tồn kho chung)
    ("tồn kho mã SP001 là bao nhiêu", "inventory_check"),
    ("còn bao nhiêu cái ABC-123", "inventory_check"),
    ("số lượng khả dụng của sản phẩm XYZ", "inventory_check"),
    ("hiện sản phẩm mã X đang có bao nhiêu trong kho", "inventory_check"),
    ("kiểm tra tồn kho mã X", "inventory_check"),
    ("check tồn kho SP001", "inventory_check"),
    ("còn hàng không mã ABC-123", "inventory_check"),
    ("mã SAMSUNG-S24 đang có bao nhiêu sản phẩm", "inventory_check"),
    ("SP001 khả dụng bao nhiêu", "inventory_check"),
    ("mỳ tôm còn bao nhiêu trong kho", "inventory_check"),
    ("điện thoại samsung còn hàng không", "inventory_check"),
    ("bút bi còn tồn bao nhiêu", "inventory_check"),
    ("check giùm mã IPHONE-15 còn mấy cái", "inventory_check"),
    ("soi giúp tồn kho con MACBOOK-PRO", "inventory_check"),
    ("kho mình còn mã 8935048 không", "inventory_check"),
    ("số dư hiện tại của mã ABC là mấy", "inventory_check"),
    ("đếm thử trên phần mềm xem mã XYZ còn mấy cái", "inventory_check"),

    # 2. LOW_STOCK (Cảnh báo cạn hàng)
    ("sản phẩm nào sắp hết hàng", "low_stock"),
    ("mặt hàng nào cần nhập thêm", "low_stock"),
    ("báo cáo tồn kho thấp", "low_stock"),
    ("hàng nào gần hết", "low_stock"),
    ("danh sách hàng sắp hết kho", "low_stock"),
    ("cần nhập thêm hàng gì", "low_stock"),
    ("mặt hàng nào đang ở mức báo động", "low_stock"),
    ("cảnh báo hàng tồn kho thấp", "low_stock"),
    ("những sản phẩm tồn kho ít", "low_stock"),
    ("hàng nào sắp cạn cần đặt thêm", "low_stock"),
    ("alert tồn kho thấp", "low_stock"),
    ("hàng nào cần restock gấp", "low_stock"),
    ("có mã nào chuẩn bị đứt hàng không", "low_stock"),
    ("lọc ra các sản phẩm sắp chạm đáy tồn kho", "low_stock"),
    ("kho sắp móm những mặt hàng nào", "low_stock"),
    ("list hàng cần lên kế hoạch mua thêm", "low_stock"),

    # 3. PRODUCT_LOCATION (Vị trí hàng)
    ("sản phẩm SP001 đang ở kệ nào", "product_location"),
    ("mã ABC cất ở đâu trong kho", "product_location"),
    ("tìm vị trí của hàng XYZ", "product_location"),
    ("IPHONE-15 đang nằm ở kệ nào", "product_location"),
    ("tìm kệ chứa sản phẩm IPHONE-15", "product_location"),
    ("mã SP001 hiện đang ở đâu", "product_location"),
    ("sản phẩm SAMSUNG đang ở khu nào", "product_location"),
    ("hàng SP001 đang nằm ở đâu trong kho", "product_location"),
    ("mỳ tôm ở kệ nào", "product_location"),
    ("điện thoại iphone đang để ở đâu", "product_location"),
    ("bánh mì để ở kệ nào", "product_location"),
    ("nước suối đang cất ở đâu", "product_location"),
    ("chỉ tôi đường đi lấy mã ABC", "product_location"),
    ("nhặt con LAPTOP-DELL ở góc nào", "product_location"),
    ("hàng IPHONE-14 đang xếp ở bin nào", "product_location"),
    ("mã 12345 nằm ở zone nào vậy", "product_location"),
    ("quét mã này thì ra kệ nào", "product_location"),

    # 4. BIN_PRODUCTS (Sản phẩm trong 1 kệ)
    ("kệ B2 đang có những sản phẩm nào", "bin_products"),
    ("kệ A1 chứa những mặt hàng gì", "bin_products"),
    ("liệt kê hàng trong kệ C3", "bin_products"),
    ("kệ B1 đang để những gì", "bin_products"),
    ("kệ C1 có những mã nào", "bin_products"),
    ("danh sách sản phẩm trong kệ B3", "bin_products"),
    ("xem nội dung kệ C2", "bin_products"),
    ("kệ B2 đang để sản phẩm gì vậy", "bin_products"),
    ("hàng hóa trong kệ A2 là gì", "bin_products"),
    ("show hàng trong kệ A1", "bin_products"),
    ("xem danh sách SKU trong kệ A1", "bin_products"),
    ("trong bin B2 có cất những gì", "bin_products"),
    ("quét kệ C3 xem có hàng gì ở trỏng", "bin_products"),
    ("đổ dữ liệu các mã đang nằm ở kệ A4", "bin_products"),
    ("kệ này đang lưu trữ các SKU nào", "bin_products"),

    # 5. ORDER_STATUS (Trạng thái đơn)
    ("đơn hàng SO-001 giao chưa", "order_status"),
    ("tiến độ đơn SO-2024-005 thế nào", "order_status"),
    ("trạng thái của đơn SO001", "order_status"),
    ("đơn SO-2024-001 đã xuất kho chưa", "order_status"),
    ("kiểm tra đơn hàng SO001", "order_status"),
    ("SO-005 đang ở bước nào rồi", "order_status"),
    ("đơn bán SO-2024 đã hoàn thành chưa", "order_status"),
    ("đơn SO-123 đã giao cho khách chưa", "order_status"),
    ("xem trạng thái SO-2024-010", "order_status"),
    ("SO-002 shipped chưa", "order_status"),
    ("đơn SO001 pending hay completed", "order_status"),
    ("khách hối đơn SO-999 tới đâu rồi", "order_status"),
    ("mã phiếu xuất SO-123 đang kẹt ở bước nào", "order_status"),
    ("check giùm mã SO-888 đi chưa", "order_status"),
    ("tình trạng phiếu SO-777", "order_status"),

    # 6. MONTHLY_MOVEMENT (Nhập xuất tháng của 1 SP)
    ("tháng này nhập xuất SP001 bao nhiêu", "monthly_movement"),
    ("biến động kho tháng này của mã ABC", "monthly_movement"),
    ("thống kê nhập xuất tháng của SP001", "monthly_movement"),
    ("báo cáo nhập xuất tháng mã XYZ", "monthly_movement"),
    ("lịch sử nhập xuất tháng hiện tại của IPHONE-15", "monthly_movement"),
    ("nhập bao nhiêu xuất bao nhiêu tháng này mã ABC", "monthly_movement"),
    ("thẻ kho tháng này SP001", "monthly_movement"),
    ("tổng nhập tổng xuất tháng của mã XYZ-PRO", "monthly_movement"),
    ("mã ABC tháng này nhập mấy cái xuất mấy cái", "monthly_movement"),
    ("tỷ lệ nhập xuất của mã MT-KOKOMI-01 là bao nhiêu", "monthly_movement"),
    ("tháng này mã SP001 xuất được mấy cái", "monthly_movement"),
    ("tổng kết trong tháng con IPHONE-15 ra vô bao nhiêu", "monthly_movement"),
    ("tháng này mã ABC-123 trôi được mấy cái", "monthly_movement"),
    ("xem data nhập xuất nguyên tháng của mã SP-88", "monthly_movement"),

    # 7. VELOCITY_REPORT (Báo cáo tốc độ bán chung)
    ("sản phẩm nào bán chạy nhất", "velocity_report"),
    ("hàng nào ế nhất hiện tại", "velocity_report"),
    ("top 5 hàng xuất chậm", "velocity_report"),
    ("mặt hàng hot nhất tháng này", "velocity_report"),
    ("báo cáo hàng bán nhanh", "velocity_report"),
    ("danh sách hàng ế ẩm", "velocity_report"),
    ("top sản phẩm bán tốt nhất", "velocity_report"),
    ("những mặt hàng nào xuất nhiều nhất", "velocity_report"),
    ("hàng nào khó bán nhất kho", "velocity_report"),
    ("liệt kê sản phẩm fast moving", "velocity_report"),
    ("liệt kê sản phẩm slow moving", "velocity_report"),
    ("top 5 sản phẩm tệ nhất về doanh số", "velocity_report"),
    ("trend dạo này mặt hàng nào đang hot", "velocity_report"),
    ("hàng nào đang đắp chiếu trong kho", "velocity_report"),
    ("lọc ra các món bán ế nhất", "velocity_report"),

    # 8. BIN_CAPACITY (Sức chứa kệ)
    ("kệ A1 còn chỗ không", "bin_capacity"),
    ("sức chứa của kệ B2 là bao nhiêu", "bin_capacity"),
    ("kệ C3 đang chứa bao nhiêu sản phẩm", "bin_capacity"),
    ("kệ A2 còn trống bao nhiêu chỗ", "bin_capacity"),
    ("thông tin kệ B1", "bin_capacity"),
    ("kệ C2 đầy chưa", "bin_capacity"),
    ("sức chứa tối đa của kệ A3 là mấy", "bin_capacity"),
    ("kệ B2 còn nhận thêm hàng được không", "bin_capacity"),
    ("kệ A1 có thể chứa thêm bao nhiêu", "bin_capacity"),
    ("tình trạng kệ B3 hiện tại", "bin_capacity"),
    ("chỗ trống còn lại của kệ B1", "bin_capacity"),
    ("kệ C3 capacity là bao nhiêu", "bin_capacity"),
    ("còn bao nhiêu slot trong kệ A1", "bin_capacity"),
    ("kệ A1 nhét thêm được không", "bin_capacity"),
    ("kệ C2 chứa kịch kim được bao nhiêu cái", "bin_capacity"),
    ("khoảng trống còn lại trên bin B3", "bin_capacity"),

    # 9. PRODUCT_VELOCITY (Tốc độ bán của 1 SP)
    ("mã SP001 bán nhanh hay chậm", "product_velocity"),
    ("hàng XYZ có phải fast moving không", "product_velocity"),
    ("IPHONE-15 đang thuộc nhóm bán chạy hay chậm", "product_velocity"),
    ("tốc độ bán của mã ABC-123 thế nào", "product_velocity"),
    ("SAMSUNG-S24 có đang bán chạy không", "product_velocity"),
    ("velocity của mã XYZ-PRO là bao nhiêu", "product_velocity"),
    ("mã ABC xuất có nhanh không", "product_velocity"),
    ("đánh giá tốc độ bán hàng của SP001", "product_velocity"),
    ("IPHONE-15 bán có tốt không", "product_velocity"),
    ("mã ABC-123 thuộc nhóm hàng nào về tốc độ", "product_velocity"),
    ("tốc độ luân chuyển của mã ABC", "product_velocity"),
    ("con IPHONE-14 này bán có trôi không", "product_velocity"),
    ("mã SP002 này là hàng hot hay hàng ế", "product_velocity"),

    # 10. MONTHLY_EXPORTED (Top xuất tháng)
    ("tháng này xuất được những sản phẩm nào", "monthly_exported"),
    ("tháng này kho xuất ra những mặt hàng gì", "monthly_exported"),
    ("danh sách hàng đã xuất tháng này", "monthly_exported"),
    ("những sản phẩm nào đã xuất đi trong tháng", "monthly_exported"),
    ("liệt kê hàng đã xuất tháng này", "monthly_exported"),
    ("tháng này bán ra những loại hàng nào", "monthly_exported"),
    ("báo cáo xuất kho tháng này", "monthly_exported"),
    ("tháng này sản phẩm nào xuất nhiều nhất", "monthly_exported"),
    ("top sản phẩm xuất nhiều nhất tháng này", "monthly_exported"),
    ("hàng nào xuất nhiều nhất trong tháng", "monthly_exported"),
    ("mặt hàng nào ra kho nhiều nhất tháng này", "monthly_exported"),
    ("tổng kết các mã đã đẩy đi trong tháng", "monthly_exported"),

    # 11. MONTHLY_IMPORTED (Top nhập tháng)
    ("tháng này nhập về những sản phẩm nào", "monthly_imported"),
    ("trong tháng này đã nhập những hàng gì", "monthly_imported"),
    ("danh sách hàng đã nhập tháng này", "monthly_imported"),
    ("tháng này kho nhập vào những mặt hàng gì", "monthly_imported"),
    ("những sản phẩm nào đã được nhập kho tháng này", "monthly_imported"),
    ("liệt kê hàng đã nhập tháng này", "monthly_imported"),
    ("báo cáo nhập kho tháng này", "monthly_imported"),
    ("hàng nhập về tháng này gồm những gì", "monthly_imported"),
    ("tháng này sản phẩm nào nhập nhiều nhất", "monthly_imported"),
    ("top sản phẩm nhập nhiều nhất tháng này", "monthly_imported"),
    ("hàng nào nhập về nhiều nhất trong tháng", "monthly_imported"),
    ("tổng kết các mặt hàng đã lùa vào kho tháng này", "monthly_imported"),

    # 12. CHECK_PRODUCT_IN_MOVEMENT (Hôm nay/Tháng này có nhập/xuất 1 SP cụ thể không)
    ("tháng này có nhập sản phẩm mỳ tôm không", "check_product_in_movement"),
    ("tháng này có xuất mỳ tôm không", "check_product_in_movement"),
    ("mỳ tôm có được nhập tháng này không", "check_product_in_movement"),
    ("tháng này iphone có được xuất không", "check_product_in_movement"),
    ("sản phẩm ABC-123 có nhập về tháng này không", "check_product_in_movement"),
    ("tháng này mã SP001 có xuất đơn nào chưa", "check_product_in_movement"),
    ("mã IPHONE-15 tháng này có giao dịch không", "check_product_in_movement"),
    ("tháng này bút bi có được nhập không", "check_product_in_movement"),
    ("nước suối tháng này có xuất chưa", "check_product_in_movement"),
    ("sản phẩm laptop tháng này có biến động không", "check_product_in_movement"),
    # ---> ĐẶC BIỆT THÊM CÁC CÂU "HÔM NAY" CHO NGHIỆP VỤ NÀY <---
    ("hôm nay có nhập iphone 15 ko", "check_product_in_movement"),
    ("sáng giờ có xuất SP001 không", "check_product_in_movement"),
    ("nay có về mã ABC-123 không", "check_product_in_movement"),
    ("hôm nay mặt hàng laptop có đi đơn nào không", "check_product_in_movement"),
    ("nay có nhập mã IPHONE-14 không", "check_product_in_movement"),
    ("hôm nay có xuất mỳ tôm đi không", "check_product_in_movement"),
    ("hôm qua tới nay có nhập nước suối chưa", "check_product_in_movement"),

    # 13. WAREHOUSE_SUMMARY (Tổng quan)
    ("tổng quan kho hôm nay thế nào", "warehouse_summary"),
    ("tình trạng kho hiện tại", "warehouse_summary"),
    ("báo cáo tổng hợp kho", "warehouse_summary"),
    ("dashboard kho hôm nay", "warehouse_summary"),
    ("tóm tắt tình hình kho", "warehouse_summary"),
    ("overview kho hiện tại", "warehouse_summary"),
    ("tổng số sản phẩm trong kho là bao nhiêu", "warehouse_summary"),
    ("cho tôi xem tổng quan kho", "warehouse_summary"),
    ("thống kê tổng hợp kho hôm nay", "warehouse_summary"),
    ("kho mình nay sao rồi", "warehouse_summary"),
    ("cập nhật số liệu tổng kho", "warehouse_summary"),

    # 14. PENDING_ORDERS
    ("có bao nhiêu đơn hàng đang chờ xử lý", "pending_orders"),
    ("những đơn nào chưa được xử lý", "pending_orders"),
    ("danh sách đơn hàng đang pending", "pending_orders"),
    ("đơn hàng nào đang chờ duyệt", "pending_orders"),
    ("có đơn hàng nào chưa xử lý không", "pending_orders"),
    ("liệt kê đơn đang chờ", "pending_orders"),
    ("đơn hàng chờ xử lý hiện tại", "pending_orders"),
    ("bao nhiêu đơn đang processing", "pending_orders"),
    ("những SO nào chưa hoàn thành", "pending_orders"),
    ("xem đơn hàng chưa xử lý", "pending_orders"),
    ("còn bao nhiêu phiếu xuất đang kẹt", "pending_orders"),

    # 15. OVERDUE_ORDERS
    ("đơn hàng nào đã quá hạn chưa giao", "overdue_orders"),
    ("có đơn nào trễ hạn không", "overdue_orders"),
    ("danh sách đơn quá hạn", "overdue_orders"),
    ("đơn hàng nào bị trễ", "overdue_orders"),
    ("những SO nào đã quá hạn", "overdue_orders"),
    ("đơn hàng trễ hạn cần xử lý gấp", "overdue_orders"),
    ("liệt kê đơn hàng quá hạn", "overdue_orders"),
    ("đơn nào đang bị delay", "overdue_orders"),
    ("đơn hàng nào chưa giao quá 3 ngày", "overdue_orders"),
    ("cảnh báo đơn hàng trễ", "overdue_orders"),
    ("có phiếu xuất nào trễ deadline không", "overdue_orders"),

    # 16. OVERLOADED_BINS
    ("kệ nào đang quá tải", "overloaded_bins"),
    ("khu nào đang đầy hàng nhất", "overloaded_bins"),
    ("kệ nào sắp hết chỗ", "overloaded_bins"),
    ("danh sách kệ đang quá tải", "overloaded_bins"),
    ("kệ nào đang gần đầy", "overloaded_bins"),
    ("cảnh báo kệ đầy", "overloaded_bins"),
    ("kho khu nào đang chật nhất", "overloaded_bins"),
    ("kệ nào không còn chỗ", "overloaded_bins"),
    ("báo cáo kệ quá tải", "overloaded_bins"),
    ("những kệ nào đã đầy 90%", "overloaded_bins"),
    ("bin nào đang báo đỏ full chỗ", "overloaded_bins"),

    # 17. PRODUCT_HISTORY
    ("lịch sử nhập xuất của SP001 7 ngày qua", "product_history"),
    ("mã ABC-123 tuần này ra vào thế nào", "product_history"),
    ("lịch sử giao dịch của IPHONE-15", "product_history"),
    ("7 ngày qua mã SP001 biến động thế nào", "product_history"),
    ("xem lịch sử kho của mã ABC", "product_history"),
    ("giao dịch gần đây của mã SP001", "product_history"),
    ("nhật ký nhập xuất mã ABC-123", "product_history"),
    ("lịch sử xuất nhập kho của IPHONE-15 gần đây", "product_history"),
    ("tuần này mã SP001 có những giao dịch gì", "product_history"),
    ("xem chi tiết nhập xuất gần đây của mã ABC", "product_history"),
    ("truy xuất log thẻ kho của SP001", "product_history"),

    # 18. NEVER_EXPORTED
    ("tháng này sản phẩm nào chưa được xuất lần nào", "never_exported"),
    ("hàng nào tháng này chưa bán được", "never_exported"),
    ("sản phẩm nào chưa xuất kho tháng này", "never_exported"),
    ("mặt hàng nào không có giao dịch xuất tháng này", "never_exported"),
    ("hàng nào chưa ra khỏi kho tháng này", "never_exported"),
    ("tháng này những mã nào không xuất được", "never_exported"),
    ("sản phẩm nào đang nằm im không xuất", "never_exported"),
    ("hàng nào chưa được bán tháng này", "never_exported"),
    ("những sản phẩm không xuất kho tháng này", "never_exported"),
    ("tháng này hàng nào không có đơn xuất", "never_exported"),
    ("list các mã đóng bụi từ đầu tháng", "never_exported"),

    # 19. DEAD_STOCK
    ("hàng nào tồn kho lâu nhất", "dead_stock"),
    ("sản phẩm nào không xuất 30 ngày qua", "dead_stock"),
    ("dead stock hiện tại là những hàng nào", "dead_stock"),
    ("hàng nào đang nằm kho lâu", "dead_stock"),
    ("sản phẩm nào tồn đọng lâu nhất", "dead_stock"),
    ("mặt hàng nào không bán được 1 tháng qua", "dead_stock"),
    ("hàng tồn kho không luân chuyển", "dead_stock"),
    ("những mã hàng không có giao dịch 30 ngày", "dead_stock"),
    ("hàng nào bị ứ đọng lâu nhất trong kho", "dead_stock"),
    ("danh sách dead stock", "dead_stock"),
    ("sản phẩm không xuất trong 1 tháng qua", "dead_stock"),
    ("hàng nào đang chết kho", "dead_stock"),
    ("xuất báo cáo hàng tồn đọng 1 tháng", "dead_stock"),

    # 20. MONTHLY_COMPARISON
    ("so sánh nhập xuất tháng này với tháng trước", "monthly_comparison"),
    ("tháng này so với tháng trước thế nào", "monthly_comparison"),
    ("nhập xuất tháng này có tốt hơn tháng trước không", "monthly_comparison"),
    ("tháng trước nhập xuất bao nhiêu so với tháng này", "monthly_comparison"),
    ("biến động kho tháng này tăng hay giảm so tháng trước", "monthly_comparison"),
    ("so sánh hiệu suất kho 2 tháng gần nhất", "monthly_comparison"),
    ("tháng này xuất nhiều hơn hay ít hơn tháng trước", "monthly_comparison"),
    ("đối chiếu nhập xuất tháng này và tháng trước", "monthly_comparison"),
    ("performance kho tháng này so tháng trước", "monthly_comparison"),
    ("đối chiếu doanh số xuất kho 2 tháng liền kề", "monthly_comparison"),

    # 21. ZONE_SUMMARY
    ("khu nào đang chứa nhiều hàng nhất", "zone_summary"),
    ("thống kê theo khu vực kho", "zone_summary"),
    ("tình trạng từng khu trong kho", "zone_summary"),
    ("khu nào còn nhiều chỗ trống nhất", "zone_summary"),
    ("zone nào đang dùng nhiều nhất", "zone_summary"),
    ("báo cáo sức chứa từng khu", "zone_summary"),
    ("tổng quan các khu vực kho", "zone_summary"),
    ("khu A đang dùng bao nhiêu phần trăm", "zone_summary"),
    ("so sánh sức chứa các khu", "zone_summary"),
    ("khu nào sắp hết chỗ nhất", "zone_summary"),
    ("tình trạng lấp đầy của các zone", "zone_summary"),

    # 22. TODAY_IMPORTED
    ("hôm nay nhập về những gì", "today_imported"),
    ("hàng nào vừa nhập kho hôm nay", "today_imported"),
    ("hôm nay có nhập hàng gì không", "today_imported"),
    ("danh sách hàng nhập hôm nay", "today_imported"),
    ("hôm nay nhập kho những sản phẩm nào", "today_imported"),
    ("hàng mới nhập hôm nay là gì", "today_imported"),
    ("hôm nay kho nhận được những gì", "today_imported"),
    ("sản phẩm nào nhập vào hôm nay", "today_imported"),
    ("nhập kho hôm nay gồm những gì", "today_imported"),
    ("báo cáo hàng cập bến hôm nay", "today_imported"),

    # 23. TODAY_EXPORTED
    ("hôm nay xuất đi những gì", "today_exported"),
    ("hàng nào vừa xuất kho hôm nay", "today_exported"),
    ("hôm nay có xuất hàng gì không", "today_exported"),
    ("danh sách hàng xuất hôm nay", "today_exported"),
    ("hôm nay xuất kho những sản phẩm nào", "today_exported"),
    ("hàng ra khỏi kho hôm nay là gì", "today_exported"),
    ("hôm nay kho giao đi những gì", "today_exported"),
    ("sản phẩm nào xuất đi hôm nay", "today_exported"),
    ("xuất kho hôm nay gồm những gì", "today_exported"),
    ("báo cáo xuất đi trong ngày", "today_exported"),

    # 24. MOST_RESERVED
    ("sản phẩm nào đang bị giữ chỗ nhiều nhất", "most_reserved"),
    ("mặt hàng nào đang reserved nhiều", "most_reserved"),
    ("hàng nào đang được đặt trước nhiều nhất", "most_reserved"),
    ("sản phẩm nào bị lock nhiều nhất", "most_reserved"),
    ("những mã hàng đang có reserved cao", "most_reserved"),
    ("hàng nào đang chờ xuất nhiều nhất", "most_reserved"),
    ("sản phẩm nào đang bị giữ cho đơn hàng nhiều nhất", "most_reserved"),
    ("reserved quantity cao nhất là mã nào", "most_reserved"),
    ("hàng nào đang bị hold nhiều nhất", "most_reserved"),
    ("những mã đang bị khóa cứng trong kho", "most_reserved")
]

sentences  = [kb[0] for kb in KNOWLEDGE_BASE]
embeddings = model.encode(sentences, normalize_embeddings=True)
index      = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings.astype(np.float32))
faiss.write_index(index, "warehouse.index")

with open("knowledge_base.pkl", "wb") as f:
    pickle.dump(KNOWLEDGE_BASE, f)

print(f"✅ Build thành công: {len(KNOWLEDGE_BASE)} mẫu câu với độ bao phủ từ lóng cao!")